FORMAT: 1A

# Pocket Node REST API Endpoint
This is the blueprint for the Pocket Node REST API Endpoint.

# Group Node
Represents the Node information and configuration, including what networks it supports.

# Node [/node]

+ Model (text/json)

        {
          "version": "0.0.1",
          "networks": ["BTC", "ETH"],
          "subnetworks": {
            "BTC": ["mainnet", "testnet"],
            "ETH": ["1", "4"]
          }
        }

## Retrieve Node Information [GET]

+ Response 200

    [Node][]

# Group Queries
A query is a transaction to read data from the specified network.
The `result` attribute in the response can be either an `Object`, an `Array`, a `String` or a `Number`.

# Queries [/queries]

## Submit a Query [POST]

+ Request  (text/json)

        {
          "network": "ETH",
          "subnetwork": "4",
          "query": {},
          "decoder": {}
        }

+ Response 200 (text/json)

        {
          "network": "ETH",
          "subnetwork": "4",
          "query": {},
          "decoder": {},
          "result": "{Object containing result}|[Array containing multiple results]|'String value'|Numeric Value",
          "decoded": false,
          "error": false,
          "error_msg": null
        }

# Group Transactions
A transaction is an operation that alters the state of the network.

# Transactions [/transactions]

## Submit a Transaction [POST]

+ Request  (text/json)

        {
          "network": "ETH",
          "subnetwork": "4",
          "serialized_tx": "0x000",
          "tx_metadata": {}
        }

+ Response 200 (text/json)

        {
          "network": "ETH",
          "subnetwork": "4",
          "serialized_tx": "0x000",
          "tx_metadata": {},
          "hash": "0x000",
          "metadata": {},
          "error": false,
          "error_msg": null
        }
